config/routes.rb
Rails.application.routes.draw do
  root 'airports#index'
  get '/airports' => 'airports#index', as: :airports
  get '/planes' => 'planes#index', as: :planes
  get '/planes/new' => 'planes#new'
  get '/pilots' => 'pilots#index', as: :pilots
  post '/planes' => 'planes#create', as: :post_plane
  get '/planes/:id/destroy' => 'planes#destroy', as: :destroy_plane
  get '/plane/:id' => 'planes#show'
  get '/baggages' => 'baggages#index', as: :baggages
  get '/baggage/:id' => 'baggages#new'
  get '/baggages/:id/edit' => 'baggages#edit', as: :edit_baggage
  patch '/baggages/:id' => 'baggages#update'
  post '/baggage/:id' => 'baggages#create', as: :create_baggage
  get '/baggages/:id/destroy' => 'baggages#destroy', as: :destroy_baggage
end

app/models/airport.rb
class Airport < ApplicationRecord
   has_many :parts
   has_many :planes, through: :parts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/available_model.rb
class AvailableModel < ApplicationRecord
end

app/models/available_pilot.rb
class AvailablePilot < ApplicationRecord
end

app/models/baggage.rb
class Baggage < ApplicationRecord
   belongs_to :plane
end

app/models/part.rb
class Part < ApplicationRecord
   belongs_to :plane
   belongs_to :airport
end

app/models/pilot.rb
class Pilot < ApplicationRecord
   belongs_to :plane
end

app/models/plane.rb
class Plane < ApplicationRecord
   has_many :parts
   has_many :airports, through: :parts
   has_one :pilot
   has_many :baggages
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
   def index
      @new_airport = Airport.new
      @airports = Airport.all
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/baggages_controller.rb
class BaggagesController < ApplicationController
   def index
      @planes = Plane.all
   end

   def new
      @new_baggage = Baggage.new
      @new_baggage.plane_id = params[:id]
      puts "Creating a new baggage for plane (id) " + @new_baggage.plane_id.to_s
   end

   def create
      @baggage = Baggage.new(baggage_params)
      @baggage.plane_id = params[:id]
      puts "Saving new baggage for plane (id) " + @baggage.plane_id.to_s
      if @baggage.count < 1000 && @baggage.count >= 1 && @baggage.weight > 0 && @baggage.save
         redirect_to baggages_path
      else
         redirect_back fallback_location: root_path
      end
   end

   def edit
      @baggage = Baggage.find(params[:id])
   end

   def update
      @baggage = Baggage.find(params[:id])
      w = params[:baggage][:weight].to_f
      c = params[:baggage][:count].to_i
      if c > 0 && c < 1000 && w > 0 && @baggage.update(weight: w, count: c)
         redirect_to planes_path
      else
         redirect_back fallback_location: root_path
      end
   end

   def destroy
      Baggage.destroy(params[:id])
      redirect_to planes_path
   end

   private
   def baggage_params
      params.require(:baggage).permit(:weight, :count)
   end
end

app/controllers/pilots_controller.rb
class PilotsController < ApplicationController
   def index

   end
end

app/controllers/planes_controller.rb
class PlanesController < ApplicationController
   protect_from_forgery with: :null_session

   def index
      @planes = Plane.all
   end

   def show
      @plane = Plane.find(params[:id])
   end

   def new
      @new_plane = Plane.new
      @models = AvailableModel.all
      @pilots = AvailablePilot.all
      b = true
      @pilots.each do |p|
         b = false
      end
      if b
         redirect_to pilots_path
      end
      @airports = Airport.all
   end

   def create
      airport_ids = params[:name][:id]
      model_name = params[:airport][:model]
      pilot_id = params[:airport][:pilot]

      puts "###################################"
      puts "###################################"
      puts "###################################"
      puts airport_ids, model_name, pilot_id
      puts "###################################"
      puts "###################################"
      puts "###################################"

      @plane = AvailableModel.find_by_model(model_name)
      @pilot = AvailablePilot.find(pilot_id)

      # create and save new plane
      @new_plane = Plane.new(model: @plane.model, image: @plane.image)
      @new_plane.save

      # create new pilot and mark it as unavailable
      @new_pilot = Pilot.new(name: @pilot.name, image: @pilot.image, plane_id: @new_plane.id)
      @new_pilot.save
      AvailablePilot.destroy(@pilot.id)

      # create association between airports and plane
      1.upto airport_ids.length - 1 do |i|
         part = Part.new(plane_id: @new_plane.id, airport_id: airport_ids[i])
         part.save
      end

      redirect_to planes_path
   end

   def destroy
      id = params[:id].to_i
      Part.destroy_by(plane_id: id)
      Baggage.destroy_by(plane_id: id)

      @pilot = Pilot.find_by_plane_id(id)
      @new_pilot = AvailablePilot.new(name: @pilot.name, image: @pilot.image)
      @new_pilot.save
      Pilot.destroy(@pilot.id)

      Plane.destroy(id)

      redirect_to planes_path
   end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baggages_helper.rb
module BaggagesHelper
end

app/helpers/pilots_helper.rb
module PilotsHelper
end

app/helpers/planes_helper.rb
module PlanesHelper
end

app/views/airports/index.html.erb
<main>
  <table>
    <tr>
      <th>Airport</th>
      <th>Planes</th>
    </tr>
    <% @airports.each do |airport| %>
      <% planes = airport.planes %>
      <tr>
        <td><%= airport.name %></td>

      </tr>
    <% end %>
  </table>
</main>

app/views/baggages/index.html.erb
<main>
  <table>
    <% maxBaggages = 0 %>
    <% @planes.each do |plane| %>
      <% if maxBaggages < plane.baggages.count %>
        <% maxBaggages = plane.baggages.count %>
      <% end %>
    <% end %>
    <tr>
      <th>Model</th>
      <th>Pilot</th>
      <th colspan="<%= maxBaggages %>">Baggages</th>
    </tr>
    <% @planes.each.with_index do |plane, index| %>
      <tr>
        <td><a href="plane/<%= plane.id %>"><%= plane.model %></a></td>
        <td><%= plane.pilot.name %></td>
        <% i = 0 %>
        <% plane.baggages.each do |b| %>
          <td><%= b.weight %>KG, <%= i += 1; b.count %> items&nbsp
            <div>
              <a href="<%= edit_baggage_path(b) %>">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                  <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                  <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                </svg>
              </a>
              <span>Edit this baggage</span>
            </div>
            <div>
              <a id="destroy-link" href="<%= destroy_baggage_path(b.id) %>">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                </svg>
              </a>
              <span>Delete this baggage</span>
            </div>
          </td>
        <% end %>
        <% i.upto maxBaggages do |i| %>
          <td>&nbsp</td>
        <% end %>
        <% new_baggage = Baggage.new(plane_id: plane.id) %>
        <%#= form_with(model: new_baggage, url: "/baggage/" + plane.id.to_s, method: "get") do |f| %>
<!--          <td>-->
            <%#= f.submit "Add Baggage", :class => "btn" %>
<!--          </td>-->
        <%# end %>
        <td>
          <div>
            <a href="<%= "/baggage/" + plane.id.to_s %>">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
              </svg>
            </a>
            <span>Add new baggage to plane <%= index + 1 %></span>
          </div>
        </td>
      </tr>
    <% end %>
  </table>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>AirlineApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="icon" type="image/png" href="https://res.cloudinary.com/dqgini3rw/image/upload/v1669001502/icon_jlosco.png">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <!--For Bootstrap-->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "baggages" %>
    <%= stylesheet_link_tag "airports" %>
    <%= stylesheet_link_tag "planes" %>
    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>
      <span><img src="https://res.cloudinary.com/dqgini3rw/image/upload/v1669001502/icon_jlosco.png" alt="airline icon"></span>
      <span><a href="<%= airports_path %>">Airports</a></span>
      <span><a href="<%= planes_path %>">Planes</a></span>
      <span><a href="<%= baggages_path %>">Baggages</a></span>
    </header>
    <%= yield %>
  </body>
</html>